<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<h1><?php echo $this->t->_('Overall system\'s status')?></h1>

<div class="globalsubbloc">
  <table class="globalstatustableversion">
    <tr>
      <td class="globalstatuskey"><img src="<?php echo $this->images_path;?>/status_domains.gif" alt="domains" /></td>
      <td class="globalstatusvalue"><strong><?php echo $this->domains?></strong> <?php echo $this->t->_('domains');?> 
          <?php if ($this->domains != $this->distinctdomains) { ?> (<?php echo $this->distinctdomains?> <?php echo $this->t->_('distincts')?>) <?php } ?></td>
    </tr>
    <tr>
      <td class="globalstatuskey"><img src="<?php echo $this->images_path;?>/status_users.gif" alt="users" /></td>
      <td class="globalstatusvalue"><strong><?php echo $this->users?></strong> <?php echo $this->t->_('users');?></td>
    </tr>   
    <tr>
      <td class="globalstatuskey"><img src="<?php echo $this->images_path;?>/status_hosts.gif" alt="hosts" /></td>
      <td class="globalstatusvalue"><strong><?php echo $this->hosts?></strong> <?php echo $this->t->_('host(s) in cluster');?></td>
    </tr>
    
  </table>
</div>

<div class="globalsubbloc">
 <table class="globalstatustable">
 <?php foreach ($this->status as $statusname => $status) {?>
  <tr>
    <td class="globalstatuskey">
      <img src="<?php echo $this->images_path?>/<?php if ($status['status'] == 'ok') {
         echo "status_ok.png";
      } else if ($status['status'] == 'warning') {
      	 echo "status_warning.png";
      } else {
      	 echo "status_critical.png";
      } ?>" alt="<?php echo $status['status'];?>" />
    </td>
    
    <td class="globalstatusvalue">
      <?php 
        echo $this->t->_($statusname.' status is ');
        if ($status['status'] == 'ok') {
          echo '<strong>'.$this->t->_($status['message']);
        } else {
          echo '<strong class="status_'.$status['status'].'" title="'.$this->t->_($status['value']).'">'.$this->t->_($status['message']);
        }
      ?>
      </strong>
    </td>
  </tr>
  <?php }?>
  
 </table>

</div>
