<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php echo $this->partial('ajax/monitorstatus/restartservice.phtml', array(
                         'status' => $this->status,
                         'process' => $this->process,
                         'slaveid' => $this->slaveid,
                         't' => $this->t,
                         'images_path' => $this->images_path
)); ?>
