<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<td colspan="2">
<table class="callouttable">
<?php foreach (array('ldapserver', 'basedn', 'binddn', 'bindpass', 'usessl') as $f) {?>
<?php echo $this->InputRow($this->form->getElement($f));?>
<?php }?>
<?php echo $this->InputRow($this->form->getElement('group'),array('post_field_text'=>$this->t->_('(leave empty to ignore)')));?>
</table>
</td>
