<p class="welcome"><?php echo $this->t->_('Welcome to SpamTagger administration panel')?></p>

<?php
$user = Zend_Registry::get('user');
$stconfig = SpamTagger_Config::getInstance();

if ($user && $user->getUserType() == 'administrator') {
?>
<div class="globalbloc" style="min-height: 0px; padding-bottom: 12px;">
     <h1>InfoBox by SpamTagger Team</h1>
     <div class="maclasseamoi" style="min-height: 20px; max-height: 240px; padding: 6px 12px; overflow-y: scroll; text-align: justify">
<?php
}

$urltoget='https://spamtagger.org/infobox/';

if ($user && $user->getUserType() == 'administrator') {
    $urltoget = $urltoget.'st-info-box.php';

    $curl = curl_init();
	curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 3);
	curl_setopt($curl, CURLOPT_TIMEOUT, 3); //timeout in seconds
    curl_setopt_array($curl, array(
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_SSL_VERIFYPEER => 0,
        CURLOPT_URL => $urltoget,
        CURLOPT_FAILONERROR => true
    ));

    $result = curl_exec($curl);
    if ($result === false) {
        echo "No text or no access to remote server.";
    } else {
        echo $result;
    }

    echo "</div></div></div>";
}

if (!$this->is_replica) {
?>
<div id="globalstatsbloc" class="globalbloc globalstatbloc">
    <div id="countsbloc1" class="countsbloc">
        <h1><?php echo $this->t->_('Today\'s counts');?></h1>
        <div id="globalstatsloaading" class="globaldataloading">
            <img src="<?php echo $this->images_path?>/loadingwhitebg.gif" alt="loading" />
        </div>
    </div>
    <div id="countsbloc2" class="countsbloc hidden"></div>
</div>
<?php
    $user = Zend_Registry::get('user');
    if ($user && $user->getUserType() == 'administrator') {
?>
<div id="globalstatusbloc" class="globalbloc globalstatusbloc">
   <h1><?php echo $this->t->_('Overall system\'s status')?></h1>
   <div id="globalstatusloaading" class="globaldataloading">
        <img src="<?php echo $this->images_path?>/loadingwhitebg.gif" alt="loading" />
   </div>
</div>
<?php

        $watchdogs = '';
        $replica = new Default_Model_Slave();
        if ($user && $user->getUserType() == 'administrator') {
            $urltoget = '/admin/downloads/watchdogs.html';
            $curl = curl_init();

            $id = 1;
            foreach ($replica->fetchAll() as $s) {
	            curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 3);
	            curl_setopt($curl, CURLOPT_TIMEOUT, 3); //timeout in seconds
                curl_setopt_array($curl, array(
                    CURLOPT_RETURNTRANSFER => 1,
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                    CURLOPT_URL => "https://". $s->getHostname() . $urltoget,
                    CURLOPT_FAILONERROR => true
                ));
                $result = curl_exec($curl);
                if ($result !== false && !preg_match('/^<!DOCTYPE/',$result) && !preg_match('/^\s*<br\/>\s*$/',$result)) {
                    $watchdogs .= "<h3>Host " . $s->getId() . " - " . $s->getHostname() . "</h3>$result<hr/>";
                }
            }
        }
        if ($watchdogs != '') {
?>
<div class="globalbloc" style="min-height: 0px; padding-bottom: 12px;">
    <h1>System Warnings (<a href="https://github.com/SpamTagger/SpamTagger-Plus/wiki/Watchdogs">Resolution advice here</a>)</h1>
    <div class="maclasseamoi" style="min-height: 20px; max-height: 240px; padding: 6px 12px; overflow-y: scroll; text-align: justify">
    <?php print $watchdogs ?>
    </div>
</div>
<?php
        }
    }
}
?>
