<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>

<?php echo $this->InputRow($this->form->getElement('use_alltrusted'));?>
<?php foreach (array('domainsToSPF', 'authservers') as $f) {?>
    <?php echo $this->InputRow($this->form->getElement($f),array('label_addclass'=>'flabeltextarea'));?>
<?php }?>
<?php echo $this->InputRow($this->form->getElement('authstring'));?>   
 
<tr>
  <td colspan="2"><hr /></td>
</tr>

<tr>
    <td class="flabel flabeltextarea flabelchecklist"><?php echo $this->t->_('Use these DNS lists')?> : </td>
    <td class="fvalue fvaluechecklist">
    <?php foreach ($this->form->_rwl_checks as $check) {?>
      <?php echo $this->InputRow($check, array('field_only'=>true,'nobox'=>'true','post_field_text'=>$check->getLabel()))?><br />
    <?php }?>
    </td>
</tr>