#!/bin/sh
cat <<EOF
set superusers="nosuperuser"
set timeout=5
set default=0

load_video
insmod raid
insmod mdraid
insmod gfxterm
insmod vbe
insmod vga
insmod video_bochs
insmod video_cirrus
terminal_output gfxterm
insmod gfxmenu
set gfxmode=1024x768
set gfxpayload=keep

insmod png
loadfont (\$root)/boot/grub/themes/spamtagger/arial12.pf2
loadfont (\$root)/boot/grub/themes/spamtagger/arial18.pf2
loadfont (\$root)/boot/grub/themes/spamtagger/courier16.pf2
set theme=(\$root)/boot/grub/themes/spamtagger/theme.txt
EOF
