<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Mentor Reka
 * @copyright 2025, SpamTagger
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
 <fieldset id="localesettings">
       <table class="ftable">
       	   <tr><td colspan="2" align="center">Please read the following important information before enabling this feature : <a href="https://support.spamtagger.org/boards/3/topics/53-auto-configuration" target="_blank">Auto-configuration</a></td></tr>
       </table>
       <hr/>
       <table class="ftable">
	  <tr><td colspan="2" align="center">Download and set reference configuration : <input name="download" id="download" value="Download" type="submit"></td></tr>
       </table>
       <hr/>
       <table class="ftable">
          <tr><td colspan="2">By enabling the auto-configuration, a part of your SpamTagger configuration will be synchronized every day with the recommended SpamTagger configuration.</td></tr>
          <?php echo $this->InputRow($this->form->getElement('autoconfiguration'));?>
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
     </fieldset>
 </form>
