<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
 <fieldset id="defaultssettings">
       <table class="ftable">
          <?php echo $this->InputRow($this->form->getElement('silent'));?>

          <?php echo $this->InputRow($this->form->getElement('scanner_timeout'),array('post_field_text' => $this->t->_('seconds') ));?>

          <tr>
            <td colspan="2"><hr /></td>
          </tr>

          <tr id="subzoneset">
            <td class="flabel"><?php echo $this->t->_('Active scanners')?> : </td>
            <td class="fvalue">
              <?php foreach ($this->form->scanners as $s) {?>
                <?php echo $s->getParam('comm_name')?><br />
              <?php }?>
            </td>
          </tr>


          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>

       </table>
     </fieldset>
 </form>