<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>&nbsp;
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
<fieldset>
       <?php echo $this->InputRow($this->form->getElement('panel'),array('field_only'=>true,'nobox'=>true));?>
       <?php echo $this->InputRow($this->form->getElement('name'),array('field_only'=>true,'nobox'=>true));?>
       <table class="ftable">
       
         <?php if ($this->form->canArchive()) {
           echo $this->InputRow($this->form->getElement('archive_mail'));?>
           <tr><td colspan="2"><hr /></td></tr>
         <?php  }?>
       
          <?php echo $this->InputRow($this->form->getElement('copyto_mail'));?>

          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
</fieldset>