<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
<fieldset>
       <table class="ftable" id="domainaddtable">
      
          <?php echo $this->InputRow($this->form->getElement('defaultvalues'));?>
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
</fieldset>