<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 */
?>
<p></p>
<p></p>
 <fieldset id="freetrial">
       <table class="ftable">
          <tr><td colspan="2"><p style="font-size:14px"><strong>Request an Enterprise Edition trial:</strong></p></td></tr>
          <tr><td colspan="2">See the "Register Enterprise Edition" section below to find out the list of main unlocked features</td></tr>
          <tr><td colspan="2" align="center"><a class="notunderlined" href="https://spamtagger.org/trial-request.html?key=Tx3kshaf7324fdD0!" target="_blank"><input type="button" class="linkrebuttonnobold" value="Enterprise Edition Trial" /></a></td></tr>
       </table>
</fieldset>
