<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
 <fieldset id="quarantinessettings">
       <table class="ftable">
          <?php foreach (array('spamretention', 'contentretention') as $f) {?>
          <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>

       </table>
     </fieldset>
 </form>