<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php if ($this->loading) {?>
<div id="dataloading">
<img src="<?php echo $this->images_path?>/loadinggrey.gif" alt="loading" />
<p><?php echo $this->t->_('Gathering data, this may take a while...')?></p>
</div>
<?php } else {?>

 <?php foreach ($this->log->getCategories() as $c) {?>

  <table class="stattable logtable">
  <tr>
   <td class="stattablehead logtablehead" colspan="2">
     <p><?php echo $this->t->_($c)?></p>
   </td>
 </tr>
 <?php foreach ($this->replicas as $replica) {?>

 <?php if (count($this->replicas) > 1) {?>
 <tr class="logrow">
   <td class="loghostfield"><?php echo $this->t->_('Host ID')?> : <?php echo $replica->getId()?></td>
   <td></td>
 </tr>
 <?php }?>
   <?php foreach ($this->logs as $log) {
     if ($log->getParam('category') == $c && $log->getParam('replica_id') == $replica->getId()) {
   	?>
    <tr class="logrow">
      <td class="lognamefield"><?php echo $log->getParam('name');?> : </td>
      <?php if ($log->getParam('file') != '') {?>
      <td class="loglinksfield"><a href="javascript:openLog('<?php echo $this->viewLink."f/".$replica->getId()."-".$log->getParam('shortfile')?>');"><?php echo $this->t->_('view')?></a> | <a href="<?php echo $this->downloadLink."f/".$replica->getId()."-".$log->getParam('shortfile')?>"><?php echo $this->t->_('download')?></a> (<?php echo $log->getSize();?>)</td>
      <?php } else {?>
      <td class="loglinksfield"><?php echo $this->t->_('N/A')?></td>
      <?php }?>
    </tr>
   <?php }}?>
 <?php }?>


 </table>
 <?php }?>
<?php }?>
