#!/bin/sh
# MySQL daemon start/stop script.

SRCDIR=$(grep 'SRCDIR' /etc/spamtagger.conf | cut -d ' ' -f3)
if [ "SRCDIR" = "" ]; then
  SRCDIR=/usr/spamtagger
fi
VARDIR=$(grep 'VARDIR' /etc/spamtagger.conf | cut -d ' ' -f3)
if [ "VARDIR" = "" ]; then
  VARDIR=/var/spamtagger
fi

# The following variables are only set for letting mariadb.server find things.

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

mode=$1 # start or stop
skip=$2

SKIPGRANT=
if [ "$skip" = "nopass" ]; then
  SKIPGRANT="--skip-grant-table"
fi

conf=$SRCDIR/etc/mariadb/my_master.cnf
datadir=$VARDIR/spool/mariadb_master
pid_file=$VARDIR/run/mariadb_master/mariadbd.pid
log_file=$VARDIR/log/mariadb_master/mariadb.log
binlog=$VARDIR/log/mariadb_master/mariadb_bin.log
socket=$VARDIR/run/mariadb_master/mariadbd.sock

prepare() {
  chown mysql:spamtagger $VARDIR/log/mariadb_master/mariadb.log >/dev/null 2>&1

  $SRCDIR/bin/dump_mariadb_config.pl >/dev/null 2>&1
}

case "$mode" in
'start')
  touch $VARDIR/run/mariadb_master.start.rs
  # Start daemon
  echo -n "  Starting master DB: "
  prepare
  if test -x mariadb_safe; then
    mariadb_safe --defaults-file=$conf --datadir=$datadir --pid-file=$pid_file --log-bin=$binlog --log-error=$log_file --socket=$socket $SKIPGRANT >/dev/null 2>&1 &
  else
    echo "Can't execute mariadb_safe"
  fi
  if [ -f $VARDIR/run/mariadb_master.rn ]; then
    rm $VARDIR/run/mariadb_master.rn
  fi
  echo "started."
  rm $VARDIR/run/mariadb_master.stopped >/dev/null 2>&1
  rm $VARDIR/run/mariadb_master.*.rs >/dev/null 2>&1
  ;;

'stop')
  touch $VARDIR/run/mariadb_master.stop.rs
  # Stop daemon. We use a signal here to avoid having to know the
  # root password.
  echo -n "  Stopping master DB: "
  if test -s "$pid_file"; then
    mariadbd_pid=$(cat $pid_file)
    #echo "Killing mariadbd with pid $mariadbd_pid"
    kill $mariadbd_pid
    # mariadbd should remove the pid_file when it exits, so wait for it.

    sleep 1
    while [ -s $pid_file -a "$flags" != aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ]; do
      [ -z "$flags" ] && echo $echo_n "Wait for mariadbd to exit$echo_c" || echo $echo_n ".$echo_c"
      flags=a$flags
      sleep 1
    done
    if [ -s $pid_file ]; then
      echo -n " gave up waiting! "
    elif [ -n "$flags" ]; then
      echo " stopped."
    fi
  else
    echo -n "No mariadbd pid file found. Looked for $pid_file. "
  fi
  kill -KILL $(pgrep -f my_master.cnf) >/dev/null 2>&1
  sleep 2
  echo "stopped."
  rm $VARDIR/run/mariadb_master.stop.rs >/dev/null 2>&1
  touch $VARDIR/run/mariadb_master.stopped
  ;;

'restart')
  touch $VARDIR/run/mariadb_master.restart.rs
  # Stop the service and regardless of whether it was
  # running or not, start it again.
  $0 stop
  $0 start $skip
  ;;

*)
  # usage
  echo "Usage: $0 start|stop|restart"
  exit 1
  ;;
esac
