<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<div class="hoststatusbloc">
<?php foreach ($this->slaves as $slave) {?>
<div class="hostbloc" id='hostbloc_<?echo $slave->getId();?>'>
 <?php  echo $this->partial('ajax/monitorstatus/hoststatus.phtml', array(
                         'slave' => $slave,
                         'images_path' => $this->images_path,
                         't' => $this->t,
                         'columns' => $this->columns,
                         'pieLink' => $this->pieLink,
                         'initial_loading' => $this->initial_loading,
                         'salt' => $this->salt
)); ?>
</div>
<div class="hidden" id="hostbloc_<?echo $slave->getId();?>_hidden"></div>
<?php }?>
</div>
