<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<td colspan="2">
<table class="callouttesttable">
<?php if (! $this->finished) { ?>
<tr>
  <td colspan="2"><img src="<?php echo $this->images_path?>/loadingwhitebg.gif" alt="loading..."></td>
</tr>
<?php }?>

<?php foreach ($this->status as $what => $data) {?>
<tr>
  <td class="flabel"><?php echo $this->t->_($what)?> : </td>
  <td class="fvalue<?php 
    if ($data['status'] == 'OK') { echo ' passedtest'; } elseif ($data['status'] == 'NOK') { echo ' failedtest'; }?>">
    <?php echo $this->t->_($data['message'])?>
  </td>
</tr>
<?php }?>
</table>
</td>
