<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<td colspan="2">
<table class="callouttesttable">

<tr>
  <td class="flabel"><?php echo $this->t->_('result')?> : </td>
  <td class="fvalue<?php 
    if ($this->data['status'] == 'OK') { echo ' passedtest'; } elseif ($this->data['status'] == 'NOK') { echo ' failedtest'; }?>">
    <?php echo $this->data['message']?>
  </td>
</tr>
<?php if (count($this->data['addresses']) > 0) {?>
  <td class="flabel"><?php echo $this->t->_('addresses')?> : </td>
  <td class="fvalue">
  <?php foreach ($this->data['addresses'] as $a) { ?>
	<?php echo $a?><br />
  <?php }?>
  </td>
<?php }?>
<?php if (count($this->data['errors']) > 0) {?>
  <td class="flabel"><?php echo $this->t->_('errors')?> : </td>
  <td class="fvalue">
  <?php foreach ($this->data['errors'] as $e) { ?>
	<?php echo $e?><br />
  <?php }?>
  </td>
<?php }?>
</table>
</td>