<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
 <fieldset id="filter">

<div class="searchpanel contentsearchpanel">
  <div class="searchfields">
    <div class="subsearch subsearchdate">
        <img src="<?php echo $this->images_path;?>/loupe.png" alt="<?php echo $this->t->_('search');?>" />
      <?php echo $this->t->_('Date')?> 
      <?php echo $this->InputRow($this->form->getElement('fd'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->InputRow($this->form->getElement('fm'),array('field_only'=>true,'nobox'=>true));?>
    <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
    </div>

  </div>
</div>
</fieldset>

</form>


<div id="logsbloc" class='stats'>

</div>