<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>&nbsp;
<fieldset>
  <table class="ftable">
         <?php if ($this->form->canArchive()) {
           echo $this->InputRow($this->form->getElement('archive_mail'));?>
           <tr><td colspan="2"><hr /></td></tr>
         <?php  }?>

          <?php echo $this->InputRow($this->form->getElement('copyto_mail'));?>

          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
  </table>
</fieldset>
