<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<fieldset>
       <table class="ftable">
         <?php echo $this->InputRow($this->form->getElement('delivery_type'));?>
         <?php echo $this->InputRow($this->form->getElement('spam_tag'),array('row_class'=>'spam_tag_row'));?>
          
         <tr><td colspan="2"><hr /></td></tr>
          
         <?php echo $this->InputRow($this->form->getElement('quarantine_bounces'));?>
          
         <tr><td colspan="2"><hr /></td></tr>
          
         <?php foreach (array('frequency', 'summary_type', 'summary_to') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f));?>
         <?php }?>   

         <tr><td colspan="2"><hr /></td></tr>
         <?php echo $this->InputRow($this->form->getElement('bypass_filtering'));?>
          
         <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
</fieldset>
