<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<fieldset>
       <table class="ftable">
       
          <?php echo $this->InputRow($this->form->getElement('language'));?>
          
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>

       </table>
</fieldset>