<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<fieldset>
       <table class="ftable">
       
          <?php echo $this->InputRow($this->form->getElement('gui_default_address'));?>
        
          <?php foreach (array('gui_displayed_spams', 'gui_displayed_days') as $f) {?>
             <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
         
          <tr><td colspan="2"><hr /></td></tr>
          
          <?php echo $this->InputRow($this->form->getElement('gui_mask_forced'));?>
          
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
</fieldset>