use st_config;

DROP TABLE IF EXISTS mta_config;

CREATE TABLE mta_config (
  set_id                            int(11) NOT NULL DEFAULT 1,
  stage                             int(2) NOT NULL DEFAULT 1,
  header_txt                        blob NOT NULL DEFAULT '',
  accept_8bitmime                   enum('true','false') NOT NULL DEFAULT 'true',
  print_topbitchars                 enum('true','false') NOT NULL DEFAULT 'true',
  return_path_remove                enum('true','false') NOT NULL DEFAULT 'true',
  ignore_bounce_after               char(10) NOT NULL DEFAULT '2d',
  timeout_frozen_after              char(10) NOT NULL DEFAULT '7d',
-- retry
  smtp_relay                        enum('true','false') NOT NULL DEFAULT 'false',
  relay_from_hosts                  blob,
  allow_relay_for_unknown_domains   tinyint(1) NOT NULL DEFAULT '0',
  no_ratelimit_hosts                blob,
  smtp_enforce_sync                 enum('true','false') NOT NULL DEFAULT 'true',
  allow_mx_to_ip                    enum('true','false') NOT NULL DEFAULT 'false',
  smtp_receive_timeout              char(10) NOT NULL DEFAULT '30s',
  smtp_accept_max_per_host          int(10) NOT NULL DEFAULT 10,
  smtp_accept_max_per_trusted_host  int(10) NOT NULL DEFAULT 20,
  smtp_accept_max                   int(10) NOT NULL DEFAULT 50,
  smtp_reserve                      int(10) NOT NULL DEFAULT 5,
  smtp_load_reserve                 int(10) NOT NULL DEFAULT 30,
  smtp_accept_queue_per_connection  int(10) NOT NULL DEFAULT 10,
  smtp_accept_max_per_connection    int(10) NOT NULL DEFAULT 100,
  smtp_conn_access                  varchar(10000) DEFAULT '*',
  host_reject                       blob,
  sender_reject                     blob,
  recipient_reject                  blob,
  user_reject                       blob,
  verify_sender                     tinyint(1) NOT NULL DEFAULT '1',
  global_msg_max_size               char(50) DEFAULT '50M',
  max_rcpt                          int(10) NOT NULL DEFAULT 1000,
  received_headers_max              int(10) NOT NULL DEFAULT 30,
  use_incoming_tls                  tinyint(1) NOT NULL DEFAULT '0',
  tls_certificate                   char(50) NOT NULL DEFAULT 'default',
  tls_use_ssmtp_port                tinyint(1) NOT NULL DEFAULT '0',
  tls_certificate_data              blob,
  tls_certificate_key               blob,
  hosts_require_tls                 blob,
  domains_require_tls_from          blob,
  domains_require_tls_to            blob,
  hosts_require_incoming_tls        blob,
  use_syslog                        tinyint(1) NOT NULL DEFAULT '0',
  smtp_banner                       varchar(255) NOT NULL DEFAULT '$smtp_active_hostname ESMTP Exim $version_number $tod_full',
  errors_reply_to                   varchar(255) DEFAULT '',
  rbls                              varchar(255),
  rbls_timeout                      int(10) DEFAULT 5,
  rbls_ignore_hosts                 blob DEFAULT '',
  bs_rbls                           varchar(255),
  rbls_after_rcpt                   tinyint(1) NOT NULL DEFAULT '1',
  callout_timeout                   int(10) DEFAULT 10,
  retry_rule                        varchar(255) NOT NULL DEFAULT 'F,4d,2m',
  ratelimit_enable                  int(1) DEFAULT '0',
  ratelimit_rule                    varchar(255) DEFAULT '30 / 1m / strict',
  ratelimit_delay                   int(10) DEFAULT 10,
  trusted_ratelimit_enable          int(1) DEFAULT '0',
  trusted_ratelimit_rule            varchar(255) DEFAULT '60 / 1m / strict',
  trusted_ratelimit_delay           int(10) DEFAULT 10,
  outgoing_virus_scan               tinyint(1) NOT NULL DEFAULT '0',
  mask_relayed_ip                   tinyint(1) NOT NULL DEFAULT '0',
  block_25_auth                     tinyint(1) NOT NULL DEFAULT '0',
  masquerade_outgoing_helo          tinyint(1) NOT NULL DEFAULT '0',
  forbid_clear_auth                 tinyint(1) NOT NULL DEFAULT '0',
  relay_refused_to_domains          blob,
  dkim_default_domain               varchar(255),
  dkim_default_selector             varchar(255),
  dkim_default_pkey                 blob,
  reject_bad_spf                    tinyint(1) NOT NULL DEFAULT '0',
  reject_bad_rdns                   tinyint(1) NOT NULL DEFAULT '0',
  dmarc_follow_reject_policy        tinyint(1) NOT NULL DEFAULT '0',
  dmarc_enable_reports              tinyint(1) NOT NULL DEFAULT '0',
  spf_dmarc_ignore_hosts            blob DEFAULT '',
  log_subject                       tinyint(1) NOT NULL DEFAULT '0',
  log_attachments                   tinyint(1) NOT NULL DEFAULT '0',
  ciphers                           varchar(255) NOT NULL DEFAULT 'ALL:!aNULL:!ADH:!eNULL:!LOW:!EXP:RC4+RSA:+HIGH:+MEDIUM:!SSLv2',
  allow_long                        tinyint(1) NOT NULL DEFAULT '1',
  folding                           tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (set_id, stage)
);

INSERT INTO mta_config SET stage=1;

INSERT INTO mta_config SET stage=2;

INSERT INTO mta_config SET stage=4;
