<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<div id="loginpanel">

  <img id="stlogo" src="<?php echo $this->images_path; ?>/login_header.png" alt="" />
  <p id="badlogin">
<?php echo $this->error; ?>
  </p>
   
<?php
$this->form->setAction($this->url());
echo $this->form;

$stlink="spamtagger.org";

?>

  <div id="loginfooter">
    <div class="copyright">&copy; <a href="https://<?php echo $stlink;?>"><?php echo $stlink; ?></a></div>
  </div>
</div>
