<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php if (count($this->informationals) ) {?>
<div class="infotitle"><?php echo $this->t->_('Information')?></div>
<ul>
<?php foreach ($this->informationals as $message) {?>
    <li>
    <strong><?php echo $message->getTitle();?></strong>
      <?php if ($message->getSlavesList() != '') { ?>(<?php echo $this->t->_('on hosts: ').$message->getSlavesList();?>)<?php }?>
      : <?php echo $message->getDescription();?>
    <?php if ($message->getLink() != '') {?> ( <a href="<?php echo $this->url($message->getLink());?>"><?php echo $this->t->_('Click here to resolve');?></a> )
    <?php }?>
    </li>
<?php }?>
</ul>
<?php }?>
