<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php foreach (array('panel', 'username', 'domain') as $f) {
 echo $this->InputRow($this->form->getElement($f),array('field_only'=>true,'nobox'=>true));;
  }?>
<?php echo $this->partial('forms/manageuser/'.strtolower($this->panel).'Form.phtml', array(
                                        'form' => $this->form,
                                        't' => $this->t,
                                        'images_path' => $this->images_path,
                                        'message' => $this->message,
                                        'domain' => $this->domain,
                                        'user' => $this->user,
                                        'urls' => $this->urls,
                                        'username' => $this->username ) ); ?>