<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php foreach (array('panel', 'address') as $f) {
  echo $this->InputRow($this->form->getElement($f),array('field_only'=>true,'nobox'=>true));
  }?>
<?php echo $this->partial('forms/manageuser/email'.strtolower($this->panel).'Form.phtml', array(
                                        'form' => $this->form,
                                        't' => $this->t,
                                        'images_path' => $this->images_path,
                                        'message' => $this->message,
                                        'email' => $this->email,
                                        'urls' => $this->urls,
                                        'address' => $this->address ) ); ?>