<?php 
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
 <ul id="generalconfigmenu">
   <?php foreach ($this->config_menu as $menu) {?>
  <li id="confmenu_<?php echo $menu->id?>" <?php if ($menu->class) { ?>class="<?php echo $menu->class?>"<?php }?> onclick="javascript:goTo('<?php echo $menu->getHref()?>');"><a href="<?php echo $menu->getHref()?>"><?php echo $menu->label;?></a></li>
   <?php }?>
 </ul>