<?php
/**
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html
 * @package SpamTagger Plus
 * @author Olivier Diserens
 * @copyright 2025, SpamTagger
 */
?>
<?php if (preg_match('/^\s*(NOK|OK|WAIT)\s+(.*)/', $this->message, $matches)) {
  if ($matches[1] == 'OK') { ?>
    <div id="flashmessage" class="fmOK"><?php echo $this->t->_($matches[2]);?></div>
  <?php } elseif ($matches[1] == 'WAIT') {?>
    <div id="flashmessage" class="fmWAIT"><?php echo $this->t->_($matches[2]);?></div>
  <?php } else { ?>
    <div id="flashmessage" class="fmNOK"><?php echo $this->t->_('an error occurred')." : ".$this->t->_($matches[2]);?></div>
  <?php }
  }
?>
